checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    environment:
        python: '3.5.0'
    dependencies:
        override:
            - pip install -r requirements-test.txt
    tests:
        override:
            -
                command:  py.test --cov=wlc wlc
                coverage:
                    file: '.coverage'
                    format: 'py-cc'
