checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    environment:
        python: '3.5.0'
    dependencies:
        before:
            - pip install requirements-test.txt
