language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"
matrix:
  include:
    - os: osx
      language: generic
sudo: false
# Perform the manual steps on osx to install python3 and activate venv
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
# commands to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# commands to run tests
script: 
  - py.test --cov=wlc wlc
after_script:
  - codecov
  - codacy-coverage
# trigger Buildtime Trend Service to parse Travis CI log
notifications:
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis
cache: pip
