os:
  - linux
  - osx
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"
matrix:
  exclude:
    - os: osx
      python: "pypy3"
    - os: osx
      python: "3.3"
    - os: osx
      python: "3.4"
sudo: false
# commands to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# commands to run tests
script: 
  - py.test --cov=wlc
after_script:
  - codecov
# trigger Buildtime Trend Service to parse Travis CI log
notifications:
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis
cache: pip
