language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3"
matrix:
  include:
    - os: osx
      language: generic
      # Perform the manual steps on osx to install python3 and activate venv
      before_install:
        - brew update
        - brew upgrade python3
        - virtualenv venv -p python3
        - source venv/bin/activate
sudo: false
# commands to install dependencies
install: 
  # Get newer pip and whell for binary caching support
  - pip install --upgrade pip wheel
  - pip install -r requirements-test.txt
# commands to run tests
script: 
  - py.test --cov=wlc wlc
after_script:
  - coverage xml
  - codecov
  - python-codacy-coverage
cache: pip
